TheProgrammingQuiz/Controllers/QuizController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

using TheProgrammingQuiz.Data.Models;
using TheProgrammingQuiz.Web.ViewModels.Questions;
using TheProgrammingQuiz.Services;
using TheProgrammingQuiz.Web.Models.AnonymousUser;
using TheProgrammingQuiz.Services.Data.Styles;
using TheProgrammingQuiz.Web.ViewModels.Styles;
using TheProgrammingQuiz.Services.Data.Timer;

namespace TheProgrammingQuiz.Web.Controllers
{
    public class QuizController : Controller
    {
        private IUserQuizTokensService userQuizTokensService;
        private readonly IQuestionService questionService;
        private readonly IUserPersonalStylesService userPersonalStylesService;
        private readonly IQuestionVoteStylesService questionVoteStylesService;
        private readonly ITimerService timerService;
        private UserManager<ApplicationUser> userManager;
        private ApplicationUser userCurrent;

        private Random rand;

        public QuizController(
            UserManager<ApplicationUser> userManager,
            IUserQuizTokensService userQuizTokensService,
            IQuestionService questionService,
            IUserPersonalStylesService userPersonalStylesService,
            IQuestionVoteStylesService questionVoteStylesService,
            ITimerService timerService)
        {
            this.userQuizTokensService = userQuizTokensService;
            this.questionService = questionService;
            this.userPersonalStylesService = userPersonalStylesService;
            this.questionVoteStylesService = questionVoteStylesService;
            this.timerService = timerService;
            this.userManager = userManager;

            this.rand = new Random();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                await this.GetCurrentUser();

                if (this.userCurrent.UserQuizToken.Lifes <= 0)
                {
                    return RedirectToAction("Index", "SkillLevel");
                }

                var currentQuestion = this.questionService.GetById<QuestionViewModel>(this.userCurrent.UserQuizToken.CurrentQuestionId);

                var userStylesCurrent = this.userPersonalStylesService.GetByUserId<UserPersonalStylesViewModel>(this.userCurrent.Id);
                currentQuestion.UserStyles = userStylesCurrent;

                var userQuestionVoteStyes = this.questionVoteStylesService.GetById<QuestionVoteStylesViewModel>(this.userCurrent.Id, currentQuestion.Id);
                currentQuestion.QuestionVoteStyles = userQuestionVoteStyes;

                currentQuestion.DisplayProgress = this.userCurrent.UserQuizToken.QuestionsPassed;
                currentQuestion.DisplayLives = this.userCurrent.UserQuizToken.Lifes;
                currentQuestion.DisplayCurrentStreak = this.userCurrent.UserQuizToken.CurrentStreak;
                currentQuestion.DisplayBestStreak = this.userCurrent.UserQuizToken.BestStreak;

                currentQuestion.IsSnakeUnlocked = this.userCurrent.UserQuizToken.IsSnakeUnlocked;

                System.Threading.Thread.Sleep(100); // Yeeeeeeeeeeeeeeeeeeeeeeeeeeeeee!!!

                currentQuestion.Timer = this.timerService.GetTimer(this.userCurrent.UserQuizTokenId);

                return View(currentQuestion);
            }
            else
            {
                if (this.HttpContext.Session.GetString(this.HttpContext.Session.Id) != null)
                {
                    var anonymousUser = JsonConvert.DeserializeObject<AnonymousUser>(this.HttpContext.Session.GetString(this.HttpContext.Session.Id));
                    if (anonymousUser.Lives > 0)
                    {
                        var currentQuestion = this.questionService.GetById<QuestionViewModel>(anonymousUser.CurrentQuestionId);

                        currentQuestion.DisplayProgress = anonymousUser.QuestionsPassed;
                        currentQuestion.DisplayLives = anonymousUser.Lives;
                        currentQuestion.DisplayCurrentStreak = anonymousUser.CurrentStreak;
                        currentQuestion.DisplayBestStreak = anonymousUser.BestStreak;

                        currentQuestion.IsSnakeUnlocked = anonymousUser.IsSnakeUnlocked;
                        currentQuestion.Timer = anonymousUser.QuizTimer;

                        return View(currentQuestion);
                    }
                }
            }

            return RedirectToAction("Index", "SkillLevel");
        }

        public async Task<object> GetCurrentUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                this.userCurrent = await userManager.FindByNameAsync(User.Identity.Name);

                var userTokens = this.userQuizTokensService.GetAll<UserQuizToken>().FirstOrDefault(i => i.Id == this.userCurrent.UserQuizTokenId);
                if (userTokens == null)
                {
                    throw new ArgumentException($"id with value {this.userCurrent.UserQuizTokenId} was not found in the Database!");
                }

                this.userCurrent.UserQuizToken = userTokens;

                return this.userCurrent;
            }
            return null;
        }
    }
}

TheProgrammingQuiz/Controllers/SnakeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

using TheProgrammingQuiz.Data.Models;
using TheProgrammingQuiz.Services;
using TheProgrammingQuiz.Web.Models.AnonymousUser;
using TheProgrammingQuiz.Web.ViewModels.UsersQuizTokens;

namespace TheProgrammingQuiz.Web.Controllers
{
    public class SnakeController : Controller
    {
        private readonly IUserQuizTokensService userQuizTokensService;
        private readonly UserManager<ApplicationUser> userManager;

        public SnakeController(
            IUserQuizTokensService userQuizTokensService,
            UserManager<ApplicationUser> userManager
            )
        {
            this.userQuizTokensService = userQuizTokensService;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            if (this.User.Identity.IsAuthenticated)
            {
                var user = await this.userManager.FindByNameAsync(this.User.Identity.Name);
                var userTokens = this.userQuizTokensService.GetById<UserQuizTokenViewModel>(user.UserQuizTokenId);

                if (userTokens.IsSnakeUnlocked == false)
                {
                    TempData["wasRedirected"] = true;
                    return RedirectToAction("Index", "Hacker");
                }

                await this.userQuizTokensService.SetSnakeStatus(user.UserQuizTokenId, false);
            }
            else
            {
                var annonmousUser = JsonConvert.DeserializeObject<AnonymousUser>(this.HttpContext.Session.GetString(this.HttpContext.Session.Id));

                if (annonmousUser.IsSnakeUnlocked == false)
                {
                    TempData["wasRedirected"] = true;
                    return RedirectToAction("Index", "Hacker");
                }

                annonmousUser.IsSnakeUnlocked = false;

                this.HttpContext.Session.SetString(this.HttpContext.Session.Id, JsonConvert.SerializeObject(annonmousUser));
            }

            return View();
        }
    }
}

TheProgrammingQuiz/Controllers/Styles/StylesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using TheProgrammingQuiz.Data.Models;
using TheProgrammingQuiz.Services;
using TheProgrammingQuiz.Services.Data.Styles;
using TheProgrammingQuiz.Web.ViewModels.Styles;

namespace TheProgrammingQuiz.Web.Controllers.Styles
{
    [Authorize]
    public class StylesController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserQuizTokensService userQuizTokensService;
        private readonly IUserPersonalStylesService userPersonalStylesService;

        public StylesController(
           UserManager<ApplicationUser> userManager,
           IUserQuizTokensService userQuizTokensService,
           IUserPersonalStylesService userPersonalStylesService)
        {
            this.userManager = userManager;
            this.userQuizTokensService = userQuizTokensService;
            this.userPersonalStylesService = userPersonalStylesService;
        }

        public async Task<IActionResult> Index()
        {
            var userCurrent = await this.userManager.FindByNameAsync(this.User.Identity.Name);
            var userStylesCurrent = this.userPersonalStylesService.GetByUserId<UserPersonalStylesViewModel>(userCurrent.Id);

            return View(userStylesCurrent);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserPersonalStylesViewModel input)
        {
            var userCurrent = await this.userManager.FindByNameAsync(this.User.Identity.Name);
            await this.userPersonalStylesService.Edit<UserPersonalStylesViewModel>(userCurrent.Id, input.QuestionColor, input.QuestionBackgroundColor, input.AnswerChoiceColor, input.LivesColor);

            return RedirectToAction("Index", "Quiz");
        }
    }
}

TheProgrammingQuiz/Views/Quiz/Index.cshtml
@model TheProgrammingQuiz.Web.ViewModels.Questions.QuestionViewModel

@{
    ViewData["Title"] = "Quiz";
}

@{
    var livesRightPositioningPercentage = 3.3;
    if (Model.DisplayLives > 9)
    {
        livesRightPositioningPercentage = 1;
    }
}

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
<script src="~/js/quiz/globalQuiz.min.js"></script>
<script src="~/js/quiz/submitAnswer.js"></script>

<div class="content" style="min-height: 600px">
    <div class="row" style="margin-right:0px">
        @*Left*@
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-2">
            <div class="eye-gif-image-container">
                <img id="left-eye-gif" class="eye-gif" src="~/images/gif.gif" alt="Let eye gif" draggable="false" />
            </div>
            <a id="left-donate" class="donate-text text-warning" href="https://streamlabs.com/volencho/tip" target="_blank" draggable="false">Donate</a>

            <div class="edit-styles-container">
                <a asp-controller="Styles" asp-action="Index"><li class="fas fa-edit" title="Edit styles"></li></a>
            </div>

            <span id="current-streak" class="streak-data-style">Current Streak: <span class="quiz-streak-value">@Model.DisplayCurrentStreak</span></span>

            @{
                var snakeClass = "btn disabled";
                if (Model.IsSnakeUnlocked)
                {
                    snakeClass = string.Empty;
                    if (Model.DisplayProgress % 24 == 0)
                    {
                        <audio src="~/audios/snake/snake_follow.mp3" autoplay>
                            Your browser does not support the audio element.
                        </audio>
                    }
                }
            }
            <div id="snake-container">
                <a role="button" id="snake-btn" class="a-btn @snakeClass" asp-controller="Snake" asp-action="Index" aria-describedby="tooltip-snake" draggable="false">
                    <img id="snake-img" src="~/images/snake-btn.png" alt="Snake button" draggable="false" />
                </a>
            </div>
            @if (Model.IsSnakeUnlocked == false)
            {
                <div id="tooltip-snake" class="tooltip" role="tooltip">Solve <strong>@(24 - (Model.DisplayProgress % 24))</strong> more to unlock!<div id="arrow" data-popper-arrow></div></div>
            }
        </div>
        @*Centre*@
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8">
            <span>
                <progress class="center-block" max="1000" value="@Model.DisplayProgress"></progress>
                <span id="questions-passed">@Model.DisplayProgress/1000</span>
            </span>
            <partial name="_QuestionCurrentPartial" model="@Model" />
        </div>
        @*Right*@
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-2">
            <div id="how-much-gif-container" hidden>
                <img id="how-much-gif" src="~/images/how-much.gif" alt="I, Robot saying how much gif" draggable="false" />
            </div>
            <div class="eye-gif-image-container">
                <img id="right-eye-gif" class="eye-gif" src="~/images/gif.gif" alt="Right eye gif" draggable="false" />
            </div>
            <a id="right-donate" class="donate-text" href="https://streamlabs.com/volencho/tip" target="_blank" draggable="false">Donate</a>
            <div id="lives-container">
                <img id="beating-heart" src="~/gifs/beating-robot-heart.gif" alt="Beating robot heart depicting lives" draggable="false" />
                <span id="lives-value" class="quiz-data-value" style="right: @livesRightPositioningPercentage%">@Model.DisplayLives</span>
            </div>

            <span id="longest-streak" class="streak-data-style">Longest Streak: <span class="quiz-streak-value">@Model.DisplayBestStreak</span></span>

            @*<partial name="_TimerPartial" model="timerCurrent" />*@
            <div id="countdown">
                <div id="tiles">

                    <span id="days">@Model.Timer.Days</span>
                    <span id="hours">@Model.Timer.Hours</span>
                    <span id="minutes">@Model.Timer.Minutes</span>
                    <span id="seconds">@Model.Timer.Seconds</span>

                </div>
                <div class="labels">
                    <li>Days</li>
                    <li>Hours</li>
                    <li>Mins</li>
                    <li>Secs</li>
                </div>
                <script>
                    var t;
                    var jsonTimer;

                    let daysElement = document.getElementById('days');
                    let hoursElement = document.getElementById('hours');
                    let minutesElement = document.getElementById('minutes');
                    let secondsElement = document.getElementById('seconds');

                    $("#next-button").on('click', (ev) => {
                        clearTimeout(t);
                        var __RequestVerificationToken = $("input[name=__RequestVerificationToken]")[0].value;
                        let json = JSON.stringify(jsonTimer);
                        $.ajax({
                            url: '/api/Timer',
                            type: "POST",
                            data: json,
                            headers: { 'X-CSRF-TOKEN': __RequestVerificationToken },
                            contentType: "application/json; charset=utf-8",
                            dataType: 'json',
                            success: function () {
                                location.reload(true);
                                // return false? => https://stackoverflow.com/questions/3715047/how-to-reload-a-page-using-javascript
                            }
                        })
                    });

                    window.addEventListener("beforeunload", function (ev) {
                        ev.preventDefault();
                        clearTimeout(t);
                        var __RequestVerificationToken = $("input[name=__RequestVerificationToken]")[0].value;
                        let json = JSON.stringify(jsonTimer);
                        $.ajax({
                            url: '/api/Timer',
                            type: "POST",
                            data: json,
                            headers: { 'X-CSRF-TOKEN': __RequestVerificationToken },
                            contentType: "application/json; charset=utf-8",
                            dataType: 'json',
                        })
                    });

                    function startTime() {
                        let days = daysElement.textContent;
                        let hours = hoursElement.textContent;
                        let minutes = minutesElement.textContent;
                        let seconds = secondsElement.textContent;

                        jsonTimer = { days: days, hours: hours, minutes: minutes, seconds: seconds }

                        updateTime(jsonTimer);

                        t = setTimeout(startTime, 1000);

                        function updateTime(timer) {
                            timer.seconds++;
                            if (timer.seconds >= 60) {
                                timer.seconds = 0;
                                timer.minutes++;
                                if (timer.minutes >= 60) {
                                    timer.minutes = 0;
                                    timer.hours++;
                                    if (timer.hours >= 24) {
                                        timer.hours = 0;
                                        timer.days++;
                                    }
                                }
                            }

                            daysElement.textContent = timer.days;
                            hoursElement.textContent = timer.hours;
                            minutesElement.textContent = timer.minutes;
                            secondsElement.textContent = timer.seconds;
                        }
                    }
                    startTime();
                </script>
            </div>

        </div>
    </div>

    @if (Model.DisplayProgress != 0 && Model.DisplayProgress % 97 == 0)
    {
        <div id="zombie-robot-container">
            <img id="animate-zombie-robot" src="~/gifs/Zombie-Robot.gif" alt="Running zombie robot gif" draggable="false" />
            <audio id="zombie-robot-audio" src="~/audios/braaaains-zombie-robot.wav">Your browser does not support the audio element.</audio>
            <script>
                setTimeout(() => {
                    goRobotZombie();
                }, 2000);

                function goRobotZombie() {
                    let zombieRobotContainer = document.getElementById("zombie-robot-container");
                    let zombieRobotElement = document.getElementById("animate-zombie-robot");
                    let zombieRobotAudio = document.getElementById("zombie-robot-audio");

                    zombieRobotAudio.play();

                    zombieRobotContainer.style.display = "block";
                    let position = 0;
                    let id = setInterval(frame, 5);

                    function frame() {
                        if (position >= 100) {
                            clearInterval(id);
                            zombieRobotContainer.style.display = "none";
                            zombieRobotElement.style.right = 0 + '%';
                            zombieRobotContainer.remove();
                        } else {
                            position += 0.1;
                            zombieRobotElement.style.right = position + '%';
                        }
                    }
                }
            </script>
        </div>
    }

    @if (Model.DisplayProgress != 0 && Model.DisplayProgress % 9 == 0)
    {
        <div id="ufo-container">
            <script src="~/js/pass-overs/ufo.js"></script>
            <img id="img-ufo-ship" src="/images/fly_overs/ufo.png" alt="Flying ufo" draggable="false" />
            <audio id="ufo-sound" src="/audios/ufo-sound.wav">Your browser does not support the audio element.</audio>
            <audio id="ufo-beam" src="/audios/ufo-beam.wav">Your browser does not support the audio element.</audio>
            <audio id="poke-sound" src="/audios/poke.wav">Your browser does not support the audio element.</audio>
            <script>
                setTimeout(() => {
                    flyUfo();
                }, 2000);
            </script>
        </div>
    }
</div>