TheProgrammingQuiz/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

using TheProgrammingQuiz.Data;
using TheProgrammingQuiz.Data.Models.Timer;
using TheProgrammingQuiz.Web.Models.AnonymousUser;
using TheProgrammingQuiz.Web.ViewModels;

namespace TheProgrammingQuiz.Web.Controllers
{
    public class HomeController : Controller
    {
        private ILogger<HomeController> logger;
        private readonly ApplicationDbContext db;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            this.logger = logger;
            this.db = db;
        }
        public IActionResult Index()
        {
            this.logger.LogInformation("24.04.2020, Friday, 12:35 PM, ATMOSPHERIC GOTHIC HORROR READING MUSIC | H.P Lovecraft, Stephen King, Edgar Allen Poe");

            if (this.HttpContext.Session.Get(this.HttpContext.Session.Id) == null)
            {
                this.HttpContext.Session.SetString(this.HttpContext.Session.Id, JsonConvert.SerializeObject(new AnonymousUser
                {
                    QuizTimer = new QuizTimer(),
                    HasUfoPassed = true,
                }));
            }

            var users = this.db.Users
                .Include(ut => ut.UserQuizToken)
                .OrderByDescending(x => x.UserQuizToken.MaximumSolved)
                .ThenByDescending(bs => bs.UserQuizToken.BestStreak)
                .ThenBy(c => c.CreatedOn)
                .Take(10)
                .ToList();

            return View(users);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TheProgrammingQuiz/Controllers/QuizController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

using TheProgrammingQuiz.Data.Models;
using TheProgrammingQuiz.Web.ViewModels.Questions;
using TheProgrammingQuiz.Services;
using TheProgrammingQuiz.Web.Models.AnonymousUser;
using TheProgrammingQuiz.Services.Data.Styles;
using TheProgrammingQuiz.Web.ViewModels.Styles;
using TheProgrammingQuiz.Services.Data.Timer;

namespace TheProgrammingQuiz.Web.Controllers
{
    public class QuizController : Controller
    {
        private IUserQuizTokensService userQuizTokensService;
        private readonly IQuestionService questionService;
        private readonly IUserPersonalStylesService userPersonalStylesService;
        private readonly IQuestionVoteStylesService questionVoteStylesService;
        private readonly ITimerService timerService;
        private UserManager<ApplicationUser> userManager;
        private ApplicationUser userCurrent;

        private Random rand;

        public QuizController(
            UserManager<ApplicationUser> userManager,
            IUserQuizTokensService userQuizTokensService,
            IQuestionService questionService,
            IUserPersonalStylesService userPersonalStylesService,
            IQuestionVoteStylesService questionVoteStylesService,
            ITimerService timerService)
        {
            this.userQuizTokensService = userQuizTokensService;
            this.questionService = questionService;
            this.userPersonalStylesService = userPersonalStylesService;
            this.questionVoteStylesService = questionVoteStylesService;
            this.timerService = timerService;
            this.userManager = userManager;

            this.rand = new Random();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                await this.GetCurrentUser();

                if (this.userCurrent.UserQuizToken.Lifes <= 0)
                {
                    return RedirectToAction("Index", "SkillLevel");
                }

                var currentQuestion = this.questionService.GetById<QuestionViewModel>(this.userCurrent.UserQuizToken.CurrentQuestionId);

                var userStylesCurrent = this.userPersonalStylesService.GetByUserId<UserPersonalStylesViewModel>(this.userCurrent.Id);
                currentQuestion.UserStyles = userStylesCurrent;

                var userQuestionVoteStyes = this.questionVoteStylesService.GetById<QuestionVoteStylesViewModel>(this.userCurrent.Id, currentQuestion.Id);
                currentQuestion.QuestionVoteStyles = userQuestionVoteStyes;

                currentQuestion.DisplayProgress = this.userCurrent.UserQuizToken.QuestionsPassed;
                currentQuestion.DisplayLives = this.userCurrent.UserQuizToken.Lifes;
                currentQuestion.DisplayCurrentStreak = this.userCurrent.UserQuizToken.CurrentStreak;
                currentQuestion.DisplayBestStreak = this.userCurrent.UserQuizToken.BestStreak;

                currentQuestion.IsSnakeUnlocked = this.userCurrent.UserQuizToken.IsSnakeUnlocked;

                System.Threading.Thread.Sleep(100); // Yeeeeeeeeeeeeeeeeeeeeeeeeeeeeee!!!

                currentQuestion.Timer = this.timerService.GetTimer(this.userCurrent.UserQuizTokenId);

                return View(currentQuestion);
            }
            else
            {
                if (this.HttpContext.Session.GetString(this.HttpContext.Session.Id) != null)
                {
                    var anonymousUser = JsonConvert.DeserializeObject<AnonymousUser>(this.HttpContext.Session.GetString(this.HttpContext.Session.Id));
                    if (anonymousUser.Lives > 0)
                    {
                        var currentQuestion = this.questionService.GetById<QuestionViewModel>(anonymousUser.CurrentQuestionId);

                        currentQuestion.DisplayProgress = anonymousUser.QuestionsPassed;
                        currentQuestion.DisplayLives = anonymousUser.Lives;
                        currentQuestion.DisplayCurrentStreak = anonymousUser.CurrentStreak;
                        currentQuestion.DisplayBestStreak = anonymousUser.BestStreak;

                        currentQuestion.IsSnakeUnlocked = anonymousUser.IsSnakeUnlocked;
                        currentQuestion.Timer = anonymousUser.QuizTimer;

                        return View(currentQuestion);
                    }
                }
            }

            return RedirectToAction("Index", "SkillLevel");
        }

        public async Task<object> GetCurrentUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                this.userCurrent = await userManager.FindByNameAsync(User.Identity.Name);

                var userTokens = this.userQuizTokensService.GetAll<UserQuizToken>().FirstOrDefault(i => i.Id == this.userCurrent.UserQuizTokenId);
                if (userTokens == null)
                {
                    throw new ArgumentException($"id with value {this.userCurrent.UserQuizTokenId} was not found in the Database!");
                }

                this.userCurrent.UserQuizToken = userTokens;

                return this.userCurrent;
            }
            return null;
        }
    }
}

TheProgrammingQuiz/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

    <html id="about-html" lang="en">
    <body class="about-body">
        <div class="content" style="color: #C8C8C8; min-height: 600px">
            <div class="panel-heading-about">
                <h2 class="panel-title">About The Creator</h2>
            </div>
            <div class="panel-body about-panel">
                <p>
                    Nobody cares who I am, so I will be short. I am a student who created this website all by myself. I want to thank <strong>Google</strong>, <strong>Stackoverflow</strong>, <strong>Wikipedia</strong> and the awesome <strong>templates</strong> for
                    their invaluable help. I hope you like it :)
                </p>
                <p><b>January 21, 2022 Edit:</b> I am also the creator of <a href="https://chessbook.me/" target="_blank" style="color: #337ab7;">Chessbook.me</a> :)</p>
            </div>
            <div class="panel-heading-about">
                <h2 class="panel-title">About The Quiz</h2>
            </div>
            <div class="panel-body about-panel">
                <p>
                    Are you up for the task? Can you pass all those <strong>1000</strong> quiz questions? If you can, and you are the first to do so,
                    you will win a <strong>special award</strong> (must have an account)! The more you solve, the more extras you will unlock. The quiz is everything related about computers,
                    but <strong>mainly about software</strong>. Almost all the famous languages are included, but I have tried to keep everything <strong>generic</strong>. One tip from me
                    is to always program "<strong>into</strong>" a language, not "<strong>in</strong>" a language (<cite>Code Complete</cite> by Steve McConnell). All the answers are
                    double checked that they are correct. Good luck!
                </p>

                <p><span style="color: green">Tip:</span> If you are using mobile, don't forget to <strong>rotate</strong> your device!</p>
            </div>
        </div>
    </body>
    </html>

TheProgrammingQuiz/Views/Home/Index.cshtml
@model List<TheProgrammingQuiz.Data.Models.ApplicationUser>

@{
    ViewData["Title"] = "Home";
}

@using Microsoft.AspNetCore.Identity;
@using Newtonsoft.Json;
@using System.Linq;
@using TheProgrammingQuiz.Data.Models;
@using TheProgrammingQuiz.Web.ViewModels.UsersQuizTokens;
@using TheProgrammingQuiz.Web.Models.AnonymousUser;
@using Microsoft.AspNetCore.Http;

@inject ApplicationDbContext db;
@inject UserManager<ApplicationUser> userManager;
@inject TheProgrammingQuiz.Services.IUserQuizTokensService userQuizTokensSerivce;

@{
    ApplicationUser userCurrent = null;
    AnonymousUser anonymousUser = null;
    if (User.Identity.IsAuthenticated)
    {
        userCurrent = await userManager.FindByNameAsync(User.Identity.Name);
        userCurrent.UserQuizToken = db.UserQuizTokens.FirstOrDefault(i => i.Id == userCurrent.UserQuizTokenId);
    }
    else
    {
        if (this.Context.Session.IsAvailable)
        {
            anonymousUser = JsonConvert.DeserializeObject<AnonymousUser>(this.Context.Session.GetString(this.Context.Session.Id));
        }
    }

    var bestQuizer = string.Empty;
}

<div class="content">
    <h1 id="the-programming-quiz" class="text-center display-1">The Programming Quiz</h1>
    <div id="home-row" class="row">
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-12">
        </div>
        <div class="col-lg-6 cold-md-5 col-sm-5 col-xs-12">
            <p id="challange-yourself-p" class="text-center lead"> Challange yourself with <strong>1000</strong> questions about programming!</p>
            <a role="button" id="start-the-quiz-btn" class="a-btn" asp-controller="SkillLevel" asp-action="Index" draggable="false">
                <img id="take-the-quiz" src="~/images/take-the-quiz.jpg" alt="Take the quiz" draggable="false" />
            </a>
            @if ((User.Identity.IsAuthenticated && userCurrent.UserQuizToken.Lifes > 0) || (anonymousUser != null && anonymousUser.Lives > 0))
            {
                <a role="button" id="continue-btn" class="btn-primary" asp-controller="Quiz" asp-action="Index" draggable="false">Continue</a>
            }

        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Top 10</h3>
                    <div class="pull-right">
                        <span class="clickable filter" data-toggle="tooltip" title="Toggle table filter" data-container="body">
                            <i class="@*glyphicon glyphicon-filter*@">
                                <i class="fas fa-users"></i>
                            </i>
                        </span>
                    </div>
                </div>
                <table class="table table-hover w-auto" id="leaderboard-table">
                    <thead id="leaderboard-table-header">
                        <tr role="row">
                            <th class="leaderboard-table-header-text-allign">#</th>
                            <th class="leaderboard-table-header-text-allign">Username</th>
                            <th class="leaderboard-table-header-text-allign">Maximum Solved</th>
                            <th class="leaderboard-table-header-text-allign">Best Streak</th>
                        </tr>
                    </thead>
                    <tbody id="leaderboard-table-body" class="text-center">
                        @{
                            int rank = 1;
                        }
                        @foreach (var user in Model)
                        {
                            var data = new Dictionary<string, string>
                                                                                                                                                                                                {
                                        { "Username", user.UserName }
                                };

                            var userTokens = this.userQuizTokensSerivce.GetById<UserQuizTokenViewModel>(user.UserQuizTokenId);
                            if (rank != 1)
                            {
                                <tr role="row">
                                    <td aria-readonly="true">@(rank++)</td>
                                    <td aria-readonly="true"> <a class="nav-link text-dark" asp-controller="Profile" asp-action="Index" asp-all-route-data="@data">@user.UserName</a></td>
                                    <td aria-readonly="true">@user.UserQuizToken.MaximumSolved</td>
                                    <td aria-readonly="true">@user.UserQuizToken.BestStreak</td>
                                </tr>
                            }
                            else
                            {
                                <tr role="row" id="best-quizer">
                                    <td>@(rank++)</td>
                                    <td aria-readonly="true">
                                        <a class="nav-link text-dark" asp-controller="Profile" asp-action="Index" asp-all-route-data="@data">
                                            <span class="circle-cell"><img id="leaderboard-crown-img" alt="Leaderboard crown" src="~/images/leaderboard-crown.png" title="#1 quizer" draggable="false" /></span>
                                            @user.UserName
                                        </a>
                                    </td>
                                    <td aria-readonly="true">@user.UserQuizToken.MaximumSolved</td>
                                    <td aria-readonly="true">@user.UserQuizToken.BestStreak</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="~/js/home.js"></script>
</div>